package com.orm;

/**
 * TJieyue generated by MyEclipse Persistence Tools
 */

public class TJieyue implements java.io.Serializable
{

	private Integer id;
	private int user_id;
	private int xueju_id;
	private int jieyueshuliang;

	private String jieyueshijian;
	private String shifouguihuan;
	private String guihuanshijian;
	private float feiyong;
	
	
	private TUser user;
	private TXueju xueju;
	
	public int getXueju_id()
	{
		return xueju_id;
	}
	public void setXueju_id(int xueju_id)
	{
		this.xueju_id = xueju_id;
	}
	public String getGuihuanshijian()
	{
		return guihuanshijian;
	}
	public void setGuihuanshijian(String guihuanshijian)
	{
		this.guihuanshijian = guihuanshijian;
	}
	
	public float getFeiyong()
	{
		return feiyong;
	}
	public void setFeiyong(float feiyong)
	{
		this.feiyong = feiyong;
	}
	public Integer getId()
	{
		return id;
	}
	
	public TXueju getXueju()
	{
		return xueju;
	}
	public void setXueju(TXueju xueju)
	{
		this.xueju = xueju;
	}
	public TUser getUser()
	{
		return user;
	}
	public void setUser(TUser user)
	{
		this.user = user;
	}
	public void setId(Integer id)
	{
		this.id = id;
	}
	public String getJieyueshijian()
	{
		return jieyueshijian;
	}
	public void setJieyueshijian(String jieyueshijian)
	{
		this.jieyueshijian = jieyueshijian;
	}
	public String getShifouguihuan()
	{
		return shifouguihuan;
	}
	
	public int getJieyueshuliang()
	{
		return jieyueshuliang;
	}
	public void setJieyueshuliang(int jieyueshuliang)
	{
		this.jieyueshuliang = jieyueshuliang;
	}
	public void setShifouguihuan(String shifouguihuan)
	{
		this.shifouguihuan = shifouguihuan;
	}
	public int getUser_id()
	{
		return user_id;
	}
	public void setUser_id(int user_id)
	{
		this.user_id = user_id;
	}
	
	
}