package com.orm;

/**
 * TBook generated by MyEclipse Persistence Tools
 */

public class TXueju implements java.io.Serializable
{

	private Integer id;
	private String bianhao;
	private String mingcheng;
	private float jiage;

	private String beizhu;
	private String del;

	public String getBeizhu()
	{
		return beizhu;
	}

	public void setBeizhu(String beizhu)
	{
		this.beizhu = beizhu;
	}

	public String getBianhao()
	{
		return bianhao;
	}

	public void setBianhao(String bianhao)
	{
		this.bianhao = bianhao;
	}

	public Integer getId()
	{
		return id;
	}

	public void setId(Integer id)
	{
		this.id = id;
	}

	public float getJiage()
	{
		return jiage;
	}

	public void setJiage(float jiage)
	{
		this.jiage = jiage;
	}

	public String getDel()
	{
		return del;
	}

	public void setDel(String del)
	{
		this.del = del;
	}

	public String getMingcheng()
	{
		return mingcheng;
	}

	public void setMingcheng(String mingcheng)
	{
		this.mingcheng = mingcheng;
	}
	
}